services:
    dev:
        build: .
        volumes:
            - .:/app
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=$MYSQL_DATABASE
            - POSTGRES_USER=$MYSQL_USER
            - POSTGRES_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - ./db/Postgres:/docker-entrypoint-initdb.d